### ISSUE TITLE
Go to Top的图片糊了点

### ISSUE THREAD

**Issue by maboloshi** [gaojr/scripts-styles#1]
https://github.com/gaojr/scripts-styles/blob/0531fbeac0ce53b8d798f27c305d96c9c0bd4399/scripts/github-go-top.user.js#L24

这个挖了个过来 不知道有没版权问题
https://thenounproject.com/icon/scroll-to-top-878621/

**Comment by gaojr** [comment]
nounproject这个有要求声明图标来源，现在用的是Loading.io里免费的svg
